# Generated by Django 2.2.10 on 2020-06-07 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import machina.core.validators
import machina.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0001_initial'),
        ('fullcalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=20, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('leagueevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='league.LeagueEvent')),
                ('stage', models.PositiveSmallIntegerField(default=0)),
                ('about', machina.models.fields.MarkupTextField(blank=True, no_rendered_field=True, null=True, validators=[machina.core.validators.NullableMaxLengthValidator(5000)])),
                ('rules', machina.models.fields.MarkupTextField(blank=True, no_rendered_field=True, null=True, validators=[machina.core.validators.NullableMaxLengthValidator(5000)])),
                ('use_calendar', models.BooleanField(default=True)),
                ('_about_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('_rules_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_tournament', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('league.leagueevent',),
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('division_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='league.Division')),
            ],
            bases=('league.division',),
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('leagueplayer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='league.LeaguePlayer')),
                ('order', models.PositiveSmallIntegerField()),
            ],
            bases=('league.leagueplayer',),
        ),
        migrations.CreateModel(
            name='TournamentEvent',
            fields=[
                ('publicevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fullcalendar.PublicEvent')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
            ],
            options={
                'abstract': False,
            },
            bases=('fullcalendar.publicevent',),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', max_length=20, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('bracket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Bracket')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('bracket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Bracket')),
                ('player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1_match', to='tournament.TournamentPlayer')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2_match', to='tournament.TournamentPlayer')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Round')),
                ('sgf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.Sgf')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_match', to='tournament.TournamentPlayer')),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
    ]
