version: "3.8"

services:
  app:
    container_name: openstudyroom-dev
    image: openstudyroom-dev
    restart: always
    build:
      context: .
      target: webserver
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
  cli:
    container_name: openstudyroom-cli
    image: openstudyroom-cli
    stdin_open: true
    build:
      context: .
      target: cli
    volumes:
      - ./:/app/
  ruff:
    container_name: openstudyroom-ruff
    image: openstudyroom-ruff
    build:
      context: .
      target: ruff
    volumes:
      - ./:/app/
    stdin_open: true
