# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([('league_event', 'order')]),
        ),
    ]
