# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueplayer',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Division'),
        ),
        migrations.AlterField(
            model_name='sgf',
            name='time',
            field=models.PositiveIntegerField(default=19),
        ),
    ]
