# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kgs_rank',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
