# Generated by Django 2.2.20 on 2021-04-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20210408_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueevent',
            name='self_join',
            field=models.BooleanField(default=True),
        ),
    ]
