# Generated by Django 2.2.20 on 2021-04-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_leagueevent_self_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueevent',
            name='rules_type',
            field=models.CharField(blank=True, choices=[('aga', 'AGA'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('new_zealand', 'New Zealand')], max_length=15, null=True),
        ),
    ]
