# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20170225_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueevent',
            name='min_match',
            field=models.SmallIntegerField(default=1),
        ),
    ]
