# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_leagueevent_min_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leagueevent',
            old_name='min_match',
            new_name='min_matchs',
        ),
    ]
