# Generated by Django 2.2.20 on 2021-04-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_leagueevent_rules_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgf',
            name='rules',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
