# Generated by Django 2.2.20 on 2021-04-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_sgf_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueevent',
            name='servers',
            field=models.CharField(blank=True, default='KGS,OGS', max_length=20, null=True),
        ),
    ]
