# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20170225_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueevent',
            options={'ordering': ['-begin_time']},
        ),
    ]
