# Generated by Django 2.2.20 on 2021-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20210413_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ffg_licence_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
