# Generated by Django 2.2.20 on 2021-05-04 20:46

from django.db import migrations, models
import machina.core.validators
import machina.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20210422_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='_informations_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='informations',
            field=machina.models.fields.MarkupTextField(blank=True, no_rendered_field=True, null=True, validators=[machina.core.validators.NullableMaxLengthValidator(2000)]),
        ),
    ]
