# Generated by Django 2.2.10 on 2020-06-07 19:33

from django.db import migrations, models
import django.db.models.deletion
import machina.core.validators
import machina.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, unique=True)),
                ('slug', models.CharField(max_length=8, unique=True)),
                ('close', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('promote', models.BooleanField(default=False)),
                ('description', machina.models.fields.MarkupTextField(blank=True, no_rendered_field=True, null=True, validators=[machina.core.validators.NullableMaxLengthValidator(4000)])),
                ('private_description', machina.models.fields.MarkupTextField(blank=True, no_rendered_field=True, null=True, validators=[machina.core.validators.NullableMaxLengthValidator(4000)])),
                ('_description_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('_private_description_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('admin_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_community', to='auth.Group')),
                ('new_user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_user_community', to='auth.Group')),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_community', to='auth.Group')),
            ],
        ),
    ]
