# Generated by Django 2.2.20 on 2021-06-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='discord_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
