# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170207_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullwidthpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
