# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_fullwidthpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullwidthpage',
            name='intro',
        ),
    ]
