from django.conf.urls import url

from . import views

app_name = 'community'

urlpatterns = [
    url(
        r'^(?P<slug>[\w.@+-]+)/$',
        views.community_page,
        name='community_page'
    ),
    url(
        r'^admin/list/$',
        views.admin_community_list,
        name='admin_community_list'
    ),
    url(
        r'^admin/create/$',
        views.admin_community_create,
        name='admin_community_create'
    ),
    url(
        r'^admin/delete/(?P<pk>[0-9]+)/$',
        views.admin_community_delete,
        name='admin_community_delete'
    ),
    url(
        r'^admin/update/(?P<pk>[0-9]+)/$',
        views.AdminCommunityUpdate.as_view(success_url='/community/admin/list/'),
        name='admin_community_update'
    ),
    url(
        r'^(?P<pk>[0-9]+)/admin/manage/$',
        views.manage_admins,
        name='manage_admins'
    ),
    url(
        r'^(?P<pk>[0-9]+)/users/$',
        views.admin_user_list,
        name='admin_user_list'
    ),
    url(
        r'^(?P<pk>[0-9]+)/invite/$',
        views.admin_invite_user,
        name='admin_invite_user'
    ),
    url(
        r'^update/(?P<pk>[0-9]+)/$',
        views.CommunityUpdate.as_view(),
        name='community_update'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/join/(?P<user_pk>[0-9]+)/$',
        views.community_join,
        name='community_join'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/quit/(?P<user_pk>[0-9]+)/$',
        views.community_quit,
        name='community_quit'
    ),
    url(
        r'^(?P<slug>[\w.@+-]+)/results/$',
        views.community_results_page,
        name='community_resutls'
    ),
    url(
        r'^$',
        views.community_list,
        name='community_list'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/league/create/$',
        views.CommunityLeagueEventCreate.as_view(),
        name='create_league'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/league/copy/(?P<copy_from_pk>[0-9]+)/$',
        views.CommunityLeagueEventCreate.as_view(),
        name='create_league'
    ),
    url(
        r'^league/(?P<pk>[0-9]+)/update/$',
        views.CommunityLeagueEventUpdate.as_view(),
        name='update_league'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/tournament/create/$',
        views.CommunityTournamentCreate.as_view(),
        name='create_tournament'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/calendar/create-event/$',
        views.CommunityEventCreate.as_view(),
        name='create_event'
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/calendar/create-category/$',
        views.CommunityCategoryCreate.as_view(),
        name='create_category'
    ),
    url(
        r'^(?P<slug>[\w.@+-]+)/calendar/iframe/$',
        views.calendar_iframe,
        name='calendar_iframe'
    ),
]
