# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fullcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerequestevent',
            name='receivers',
            field=models.ManyToManyField(related_name='fullcalendar_gamerequestevent_related_receiver', related_query_name='fullcalendar_gamerequestevents_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamerequestevent',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullcalendar_gamerequestevent_related_sender', related_query_name='fullcalendar_gamerequestevents_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameappointmentevent',
            name='users',
            field=models.ManyToManyField(related_name='fullcalendar_gameappointmentevent_related', related_query_name='fullcalendar_gameappointmentevents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availableevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
