# Generated by Django 2.2.20 on 2021-04-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('fullcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicevent',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
