# https://docs.github.com/en/actions/guides/building-and-testing-python

name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.7'
        cache: 'pip'

    - name: install dependencies
      run: pip3 install --quiet --requirement requirements_dev.txt

    - name: pytest
      run: ./manage.py makemigrations && pytest --create-db

    - run: ruff check --format=github .
